### ISSUE TITLE
Create actual OSM query from filters

### ISSUE THREAD

**Issue by kellyi** [azavea/idb-osm-extraction-tool#10]
Using the dropdown filters and the area of interest, replace the mocked OSM query from #6 with one that's generated according to the user's selections. Ensure that #7 and #8 continue to work as before

**Comment by mmcfarland** [comment]
We've gotten authorization to implement the official feature list using this list:

https://docs.google.com/spreadsheets/d/1XV3-YhYLksP-Bog_zb4e7bGm8Hxmil1bzpDYOh3S1yA/edit?usp=sharing
