### ISSUE TITLE
Add Netlify account for application

### ISSUE THREAD

**Issue by mmcfarland** [azavea/idb-osm-extraction-tool#11]
This is a purely static frontend that consumes a 3rd party API backend.  Ultimate production domain unknown at the moment.

**Comment by hectcastro** [comment]
Do you think we should attempt to consolidate this app under an Azavea Netlify account, or setup a client specific one so that we can handoff (we can add ourselves as admins if we go this route)?

**Comment by mmcfarland** [comment]
There's neither an expectation or easily identifiable owner (the "client" is the client of our client), so I would defer to convenience for us, whichever one that is.

I can dig up a contact to establish an account if that turns out to be more ideal.

**Comment by hectcastro** [comment]
Thanks. We'll add it to the existing one for the systems account.

**Comment by kellyi** [comment]
Out of curiosity I took a quick look at deploying a React application with Netlify and it seems like our usual Docker/cibuild workflow may not work there. If that's true, we could just adjust this script to make a bundle:

https://github.com/azavea/idb-osm-extraction-tool/blob/develop/src/app/package.json#L8
