### ISSUE TITLE
Setup map & sidebar

### ISSUE THREAD

**Issue by kellyi** [azavea/idb-osm-extraction-tool#2]
Following the wireframes, set up the map and sidebar components

Configure the map to use the OSM basemap & be centered in the proper place

Configure the sidebar to have a header & extract button, but no dropdowns, roughly matching the wireframes

**Comment by rajadain** [comment]
Wireframes are available here: https://app.goabstract.com/share/7fa73ef2-0b8e-4df0-9dbc-adda9f3cb47c

![image](https://user-images.githubusercontent.com/1430060/42771848-7f478568-88f6-11e8-9160-e425a298a0b2.png)
