### ISSUE TITLE
Shapefiles produced from extract are not valid

### ISSUE THREAD

**Issue by mmcfarland** [azavea/idb-osm-extraction-tool#33]
Upon downloading a shapefile converted from OSM->JSON feature results in errors when opening.  The error from multiple systems indicates that this is due to a discrepancy between the count of spatial features and the rows in the DBF.  The geojson that is being converted appears to be valid.

Investigate if the current shapefile library is being used incorrectly
 - are we settings the `points` | `lines` | `polygon` properties correctly?
 - are we handling the `tags` attribute of `properties` properly?  Do they need to be flattened?

If the problem seems endemic to this library, experiment with alternatives.

**Comment by kellyi** [comment]
Adding a `flatProperties: true` option to the osmtogeojson invocation as specified here -- https://github.com/tyrasd/osmtogeojson#osmtogeojson-data-options -- cures the problem with the nested propeties for points and other geometries.

It appears that there's a bug in shpwrite's handling of linestrings whereby it concats them all into a single polyline feature: https://github.com/mapbox/shp-write/issues/44#issuecomment-310360267

**Comment by kellyi** [comment]
I tried out adding a couple of patches to shp-write to deal with polygons and linestrings and it seems to have enabled the shapefile outputs to have valid shapefiles and to show multiple features if they have them

https://github.com/kellyi/shp-write/tree/ki/patch-shape-parsing

Testing via mapshaper worked for the polygons and linestrings and most of the points, but I did encounter a recursion error when trying to import a specific points file.
