### ISSUE TITLE
Add OSM based geocoder

### ISSUE THREAD

**Issue by mmcfarland** [azavea/idb-osm-extraction-tool#9]
Additionally, allow the geocoder to work on coordinates as Guyana has many remote areas which may not be present in a Gazetteer.

**Comment by kellyi** [comment]
Looks like autocomplete isn't supported/is forbidden according to the terms of the OSM Nominatim geocoder https://operations.osmfoundation.org/policies/nominatim/

To simplify things for the initial stage of work, we decided to try using Esri Leaflet geocoder. @mmcfarland checked and it seems to have robust enough results for Guyana.
